### ISSUE TITLE
Time information for Platform support page

### ISSUE THREAD

**Issue by apopiak** [rust-lang/rust-forge#108]
When looking at the Tier 3 information on the [platform support page](https://forge.rust-lang.org/platform-support.html) I don't have any idea when this was last updated. It would be really helpful if I could check for e.g. Solaris when `x86_64-sun-solaris` was built successfully and with which version of the compiler.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Tier 3 platforms are not built in CI, so if platform has stopped working we have no way to provide that information. I'd recommend getting in contact with those involved with working on support for the specific platforms you're interested.

**Comment by apopiak** [comment]
@XAMPPRocky Thank you for the answer, but I think you misunderstood my intention. The fact that Tier 3 platforms are not built in CI is exactly the reason why it would be useful to add the last time it was known to successfully build.

I know that you might not have this information for past builds, but it would already be useful to add it for upcoming successful builds. You might ask people that submit the successful build information to add the Rust version built and the date when they were successful.

This is thus a suggestion for questions to ask people contributing successful Tier 3 builds.

**Comment by XAMPPRocky** [comment]
@apopiak I would find that information would be more useful if it was part of a specific platform's own documentation rather than in Rust Forge, this information would be hard to verify. I would prefer to stick to more objective measures of support such as rustup's target list, which would also be guaranteed up to date as it integrates with our current release infrastructure.
