### ISSUE TITLE
So you want to deprecate a feature?

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust-forge#140]
... section would be nice to have describing the process to deprecate e.g. a library API.

**Comment by ehuss** [comment]
I'm going to close since there is now some documentation on deprecation at https://rustc-dev-guide.rust-lang.org/stability.html. It is incomplete, but at least a start. For specific followup, I'm going to suggest filing issues or PRs at https://github.com/rust-lang/rustc-dev-guide (or maybe https://github.com/rust-lang/std-dev-guide).
