### ISSUE TITLE
Discussion: zulip stream naming convention causing 'understanding friction'

### ISSUE THREAD

**Issue by Ben-PH** [rust-lang/rust-forge#317]
Zulip is new to me, and my first experience included having to parse the 't-' prefix in the stream names. . This is the first time coming across 't-', and it left me with a minor sense of 'I'm an outsider here', which I believe is considered an undesirable outcome by the rust community . The biggest contributor to this, in my experience was this:

>  using `ctrl-f t-` to find explanations is problematic due to '**t-**$name' clashing with 'rus**t-**$foo' 

thus, when searching for the answer to "what is this t- prefix?" in the rust-forge book, results were polluted, obfuscating the section that explains it.

My take on why it caused a "sense of outsider":

 * It seems to be an important part of how this zulip channel is organized
 * I have not come across it anywhere else.
 * Due to above mentioned clashing of 't-$team_name' and 'rust-$topic', a feeling that this was an 'insider-knowledge' started generating

Proposed solution: change the 't-' prefix to 'tm-', ideally such that there is little friction when reverting back to 't-' if desired.

Reasoning:

 * searching for 'tm-' will no longer clash in zulip-use documentation (at time of writing). Possibly in other important locations also.
 * 'tm' is a stronger hint than 't', giving a reduced sense of obfuscation of meaning
 * as zulip newcomers become more prominent in the user-base, not knowing 't-' becomes less exclusionary. At that point, reverting back to 't-' might be desired. 

Caveats:
It might be worth considering adding a note to the zulip documentation the reasoning for 'tm-' over 't-'.

**Comment by Ben-PH** [comment]
I would like to add: I really like there being a 2-char team-name prefix. Makes things MUCH clearer when you realize what it is. I would see 'tm-' as a more temporary thing during the community uptake period, where the broader community is still becoming familiar with it.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I think whether it should `t-` or `tm-` would be better discussed on Zulip in the `#zulip` channel. Since it's more likely that the right people will see it.

Personally I lean to keeping `t-` if only for historical reasons. Regardless I think we can try to address some of that by having a section that explains the naming scheme.

Generally I think we'd be well served with a "jargon" page, filled with terms and shorthands like this.

**Comment by Ben-PH** [comment]
I was originally going to post in zulip, but started feeling like a formal submission of an issue. I'll Copy-paste with a link to this issue shortly, and comment there.

**Comment by Ben-PH** [comment]
[link to Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/122653-zulip/topic/new-user.20friction.20from.20stream.20naming.20conventions/near/190467921)

**Comment by eddyb** [comment]
`t-` is a weird spelling of `T-` IMO, which is the label prefix we use in `rust-lang/rust`.

But also, it's an unnecessary prefix, `compiler` and `compiler/...` look fine to me.
For comparison, one Discord there's `#compiler`, which also works fine.

**Comment by XAMPPRocky** [comment]
I don't think we should be removing the prefixes because for certain teams it makes the room's topic ambiguous and more prone to spam or offtopic discussion. E.g. `#community` is not obvious that it's for the community team and not the community. We've been adding `-team` a few of the channels on the discord to address this exact issue.
